// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CPriceItem struct {
	Mtype                int32    `protobuf:"zigzag32,1,opt,name=mtype,proto3" json:"mtype,omitempty"`
	Oriname              string   `protobuf:"bytes,2,opt,name=oriname,proto3" json:"oriname,omitempty"`
	Count                int32    `protobuf:"zigzag32,3,opt,name=count,proto3" json:"count,omitempty"`
	InnerParam           int32    `protobuf:"zigzag32,4,opt,name=inner_param,json=innerParam,proto3" json:"inner_param,omitempty"`
	Exinfo               int32    `protobuf:"zigzag32,5,opt,name=exinfo,proto3" json:"exinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPriceItem) Reset()         { *m = CPriceItem{} }
func (m *CPriceItem) String() string { return proto.CompactTextString(m) }
func (*CPriceItem) ProtoMessage()    {}
func (*CPriceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *CPriceItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPriceItem.Unmarshal(m, b)
}
func (m *CPriceItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPriceItem.Marshal(b, m, deterministic)
}
func (m *CPriceItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPriceItem.Merge(m, src)
}
func (m *CPriceItem) XXX_Size() int {
	return xxx_messageInfo_CPriceItem.Size(m)
}
func (m *CPriceItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CPriceItem.DiscardUnknown(m)
}

var xxx_messageInfo_CPriceItem proto.InternalMessageInfo

func (m *CPriceItem) GetMtype() int32 {
	if m != nil {
		return m.Mtype
	}
	return 0
}

func (m *CPriceItem) GetOriname() string {
	if m != nil {
		return m.Oriname
	}
	return ""
}

func (m *CPriceItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CPriceItem) GetInnerParam() int32 {
	if m != nil {
		return m.InnerParam
	}
	return 0
}

func (m *CPriceItem) GetExinfo() int32 {
	if m != nil {
		return m.Exinfo
	}
	return 0
}

type User struct {
	Pwd                  string        `protobuf:"bytes,1,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Item                 *CPriceItem   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Awards               []*CPriceItem `protobuf:"bytes,3,rep,name=awards,proto3" json:"awards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetItem() *CPriceItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *User) GetAwards() []*CPriceItem {
	if m != nil {
		return m.Awards
	}
	return nil
}

type MsgCfgBase struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rate                 float32  `protobuf:"fixed32,2,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCfgBase) Reset()         { *m = MsgCfgBase{} }
func (m *MsgCfgBase) String() string { return proto.CompactTextString(m) }
func (*MsgCfgBase) ProtoMessage()    {}
func (*MsgCfgBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *MsgCfgBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCfgBase.Unmarshal(m, b)
}
func (m *MsgCfgBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCfgBase.Marshal(b, m, deterministic)
}
func (m *MsgCfgBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCfgBase.Merge(m, src)
}
func (m *MsgCfgBase) XXX_Size() int {
	return xxx_messageInfo_MsgCfgBase.Size(m)
}
func (m *MsgCfgBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCfgBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCfgBase proto.InternalMessageInfo

func (m *MsgCfgBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCfgBase) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type MsgCfgTest struct {
	Id                   int32         `protobuf:"zigzag32,1,opt,name=id,proto3" json:"id,omitempty"`
	Base                 *MsgCfgBase   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Open                 bool          `protobuf:"varint,3,opt,name=open,proto3" json:"open,omitempty"`
	Awards               []*CPriceItem `protobuf:"bytes,4,rep,name=awards,proto3" json:"awards,omitempty"`
	Params               []int32       `protobuf:"zigzag32,5,rep,packed,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgCfgTest) Reset()         { *m = MsgCfgTest{} }
func (m *MsgCfgTest) String() string { return proto.CompactTextString(m) }
func (*MsgCfgTest) ProtoMessage()    {}
func (*MsgCfgTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *MsgCfgTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCfgTest.Unmarshal(m, b)
}
func (m *MsgCfgTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCfgTest.Marshal(b, m, deterministic)
}
func (m *MsgCfgTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCfgTest.Merge(m, src)
}
func (m *MsgCfgTest) XXX_Size() int {
	return xxx_messageInfo_MsgCfgTest.Size(m)
}
func (m *MsgCfgTest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCfgTest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCfgTest proto.InternalMessageInfo

func (m *MsgCfgTest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgCfgTest) GetBase() *MsgCfgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *MsgCfgTest) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *MsgCfgTest) GetAwards() []*CPriceItem {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCfgTest) GetParams() []int32 {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*CPriceItem)(nil), "pb.CPriceItem")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*MsgCfgBase)(nil), "pb.MsgCfgBase")
	proto.RegisterType((*MsgCfgTest)(nil), "pb.MsgCfgTest")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xbd, 0x4e, 0x33, 0x31,
	0x10, 0xd4, 0xd9, 0x97, 0x7c, 0x5f, 0x36, 0x52, 0x04, 0x16, 0x42, 0xee, 0x38, 0x5d, 0x81, 0x52,
	0xa5, 0x00, 0x9e, 0x20, 0x69, 0xa0, 0x40, 0x8a, 0x2c, 0xa8, 0x91, 0x2f, 0xb7, 0x89, 0x5c, 0xf8,
	0x47, 0xb6, 0x51, 0xe0, 0x19, 0x68, 0x79, 0x60, 0xe4, 0xbd, 0x44, 0x49, 0x81, 0xe8, 0x66, 0x76,
	0xf6, 0x6e, 0x66, 0xc7, 0x30, 0xb1, 0x69, 0xb7, 0x08, 0xd1, 0x67, 0x2f, 0x58, 0xe8, 0xda, 0xaf,
	0x0a, 0x60, 0xb5, 0x8e, 0x66, 0x83, 0x4f, 0x19, 0xad, 0xb8, 0x82, 0x91, 0xcd, 0x9f, 0x01, 0x65,
	0xd5, 0x54, 0xf3, 0x4b, 0x35, 0x10, 0x21, 0xe1, 0x9f, 0x8f, 0xc6, 0x69, 0x8b, 0x92, 0x35, 0xd5,
	0x7c, 0xa2, 0x8e, 0xb4, 0xec, 0x6f, 0xfc, 0xbb, 0xcb, 0x92, 0x0f, 0xfb, 0x44, 0xc4, 0x0d, 0x4c,
	0x8d, 0x73, 0x18, 0xdf, 0x82, 0x8e, 0xda, 0xca, 0x9a, 0x34, 0xa0, 0xd1, 0xba, 0x4c, 0xc4, 0x35,
	0x8c, 0xf1, 0xc3, 0xb8, 0xad, 0x97, 0x23, 0xd2, 0x0e, 0xac, 0xed, 0xa1, 0x7e, 0x4d, 0x18, 0xc5,
	0x05, 0xf0, 0xb0, 0xef, 0x29, 0xc4, 0x44, 0x15, 0x28, 0x5a, 0xa8, 0x4d, 0x46, 0x4b, 0xfe, 0xd3,
	0xbb, 0xd9, 0x22, 0x74, 0x8b, 0x53, 0x6c, 0x45, 0x9a, 0xb8, 0x85, 0xb1, 0xde, 0xeb, 0xd8, 0x27,
	0xc9, 0x1b, 0xfe, 0xcb, 0xd6, 0x41, 0x6d, 0x1f, 0x00, 0x9e, 0xd3, 0x6e, 0xb5, 0xdd, 0x2d, 0x75,
	0x42, 0x21, 0xa0, 0xa6, 0xcb, 0x06, 0x33, 0xc2, 0x65, 0x16, 0x75, 0x1e, 0xae, 0x65, 0x8a, 0x70,
	0xfb, 0x5d, 0x1d, 0x3f, 0x7b, 0xc1, 0x94, 0xc5, 0x0c, 0x98, 0xe9, 0x0f, 0x35, 0x31, 0x43, 0x01,
	0x3b, 0x9d, 0xf0, 0x3c, 0xe0, 0xc9, 0x44, 0x91, 0x56, 0x7e, 0xeb, 0x03, 0x3a, 0x2a, 0xeb, 0xbf,
	0x22, 0x7c, 0x16, 0xba, 0xfe, 0x2b, 0x74, 0xa9, 0x8c, 0xda, 0x4c, 0x72, 0xd4, 0xf0, 0x52, 0xd9,
	0xc0, 0x96, 0xec, 0x91, 0x77, 0x63, 0x7a, 0xcf, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b,
	0x4a, 0x84, 0x49, 0xdc, 0x01, 0x00, 0x00,
}
